export const ACTION_PRODUCT_FETCH = 'ACTION_PRODUCT_FETCH';
export const ACTION_FETCH_ONE_PRODUCT = 'ACTION_FETCH_ONE_PRODUCT';

export const ACTION_ADD_TO_CART = 'ACTION_ADD_TO_CART';
export const ACTION_REMOVE_FROM_CART = 'ACTION_REMOVE_FROM_CART';
export const ACTION_REMOVE_ALL_PRODUCT_FROM_CART =
  'ACTION_REMOVE_ALL_PRODUCT_FROM_CART';

export const ACTION_ERROR = 'ACTION_ERROR';

export const ACTION_FILTER_CATEGORY = 'ACTION_FILTER_CATEGORY';
export const ACTION_SEARCH_PANEL = 'ACTION_SEARCH_PANEL';
